version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: asdfQWER1234
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/eventsdb

volumes:
  mongodb_data_container: