export enum EventFormActionsType {
  EVENT_FORM_SUBMIT_START = "EVENT_FORM_SUBMIT_START",
  EVENT_FORM_SUBMIT_SUCCESS = "EVENT_FORM_SUBMIT_SUCCESS",
  EVENT_FORM_SUBMIT_FAILURE = "EVENT_FORM_SUBMIT_FAILURE",
  EVENT_FORM_UPDATE = "UPDATE_EVENT_FORM",
  EVENT_FORM_TOUCHED_UPDATE = "EVENT_FORM_TOUCHED_UPDATE",
}
